apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  type: "oci"
  interval: 60m
  url: oci://cr.yandex/yc-marketplace/yandex-cloud/vault/chart
