apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  releaseName: jenkins
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: jenkins
      version: "5.8.24" 
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      service:
        type: ClusterIP
      persistence:
        enabled: true
        storageClass: "local-path" 
        size: 10Gi
    agent:
      enabled: true
      replicaCount: 2
      image: "jenkins/inbound-agent:latest"