apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      containers:
      - name: jenkins-agent
        image: jenkins/inbound-agent:4.10-1
        env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080"
        - name: JENKINS_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkins-agent-secret
              key: jenkins-agent-secret
        - name: JENKINS_AGENT_NAME
          value: "static-agent"
