apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
      extraEnvironmentVars:
        VAULT_SEAL_TYPE: ""
        YANDEXCLOUD_KMS_KEY_ID: ""
        YANDEXCLOUD_SERVICE_ACCOUNT_KEY_FILE: ""
      image:
        repository: "hashicorp/vault"
        tag: "1.19.0"
        pullPolicy: IfNotPresent
      ui:
        enabled: true
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 10Gi