apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/deploy/vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
    namespace: flux-system
  targetNamespace: vault
