apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: "0.29.1"      
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    global:
      tlsDisable: true   
    server:
      ha:
        enabled: true
        replicas: 3
      haStorageType: "raft"
      dataStorage:
        enabled: true
        storageClass: "standard"  
      extraConfig: |
        ui = true
        listener "tcp" {
          address       = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"
          tls_disable   = 1
        }
        storage "raft" {
          path    = "/vault/data"
          node_id = "vault-0"
        }
