apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m
  path: "./vault"
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3s-gitops
    namespace: flux-system
  configMapGenerator:
    - name: vault-values
      files:
        - values.yaml
